### PR TITLE
Fix opening multiple screens when navigating

### LINKED ISSUE #171: Navigation bug
### Description

A bug with navigation has been detected.

**Steps for reproduce:**

1. Log in to the app
2. Go to "Settings" screen
3. Press the "Open source licenses" button quickly several times
4. Go to "Open source licenses" screen
5. Press the back arrow 1 time in the appbar

**Expected result:**
The settings page should open

**Actual result**
The settings page does not open. It opens only after a few clicks.

**Similar behavior can be observed on other screens.**

### PR DESCRIPTION
**Pull request by pcfaktor**
## Summary

- All navigation callbacks are invoked through `navDestination` state handling instead of passing callbacks to Composables directly.
- For screens that do not support landscape orientation, portrait orientation is forced.
- The `feature` package has been structured, and package names have been aligned with the [Java package naming convention](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html).

## Reasons

- Passing the navigation callback to composable causes multiple instances of the screen to open if you click quickly. Calling callbacs during state processing solves this problem. In addition, the navigation implementation becomes more consistent.
- Currently, some screens do not support landscape orientation. Simply wrapping the layout in a scrollable `Column` doesn't solve the problem and generates others (like [TextFields issues](https://m3.material.io/components/text-fields/guidelines#7fb524c4-8f1e-45a2-a660-459dc902b3ad)), as well as degrading the UX. Until we get back to refactoring these screens, they are better fixed in portrait orientation.

## References

- closes #171

### CODE REVIEW

File: app/src/main/kotlin/com/softteco/template/utils/LockScreenOrientation.kt [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+    val originalOrientation = activity.resources.configuration.orientation
+
+    DisposableEffect(orientation) {
+        activity.requestedOrientation = orientation
+
+        onDispose {
+            activity.requestedOrientation = originalOrientation
+        }
+    }
+}
```
Comment (EvgeniyFilippov) [inline app/src/main/kotlin/com/softteco/template/utils/LockScreenOrientation.kt:19]: It looks like most of the screens do not support landscape orientation.
It seems to me that in this case it would be better to do so:

1. Add to Manifest
```kotlin
android:screenOrientation="portrait"
```
2. Rename and edit the method:

```kotlin
@Composable
fun UnlockScreenOrientation() {
    val activity = LocalContext.current.getActivity() ?: return
    val originalOrientation = activity.resources.configuration.orientation

    DisposableEffect(Unit) {
        activity.requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_SENSOR

        onDispose {
            activity.requestedOrientation = originalOrientation
        }
    }
}
```
3. To call UnlockScreenOrientation() method only on screens that support landscape orientation

**Review by EvgeniyFilippov — APPROVED** [review]

File: app/src/main/kotlin/com/softteco/template/utils/LockScreenOrientation.kt (hunk 1 above)
Comment (EvgeniyFilippov) [reply app/src/main/kotlin/com/softteco/template/utils/LockScreenOrientation.kt:19]: Apparently, my example will include support for landscape orientation on all screens... But I think the idea is clear)) I'm not sure if this can be done.

**Review by bstolyarov — APPROVED** [review]

File: app/src/main/kotlin/com/softteco/template/utils/LockScreenOrientation.kt (hunk 1 above)
Comment (pcfaktor) [reply app/src/main/kotlin/com/softteco/template/utils/LockScreenOrientation.kt:19]: Yes, there's more boilerplate code now, and I've thought about that. But:
1. The ratio of affected to unaffected screens is such because the project contains only basic functions. But it is being designed to be scalable. And the ratio will change when the project is used for its intended purpose.
2. To provide good UX, it is better to have support for both orientations. So right now we can consider the lack of landscape orientation support as a problem of a specific screen. And this implementation is just a temporary hack. When we go back to refactoring these screens and implement landscape orientation support, the changes will not affect the already correct screens.
