### PR TITLE
Fix navigation after login 

### LINKED ISSUE #151: Fix navigation after login
**Preconditions:**
1. Log out from the app.
2. Remove the app from recents. 

**Steps:** 
1. Open the app
2. Login (after login you should be on the Home screen)
3. Click on the Profile screen
4. Click on the Settings screen
5. Click on the Home screen
6. Click back hardware button

**Expected result:** The app is closed
**Actual result:** The app opens the Settings screen

### PR DESCRIPTION
**Pull request by anastasiaShpakava**
## Summary
Fixed bug in notification after login.

## Reasons
Closing the app when the system back button is pressed can help users quickly exit the app and return to the device's home screen or previous task. It's also a common design pattern to prevent users from getting stuck in a loop of navigating back through screens indefinitely.

## References
closes #151 .

### CODE REVIEW

**Review by EvgeniyFilippov — APPROVED** [review]

**Review by bstolyarov — CHANGES_REQUESTED** [review]
Has a wrong behavior

File: app/src/main/kotlin/com/softteco/template/MainActivity.kt [hunk 1]
```diff
@@ -49,7 +49,7 @@ class MainActivity : ComponentActivity() {
                 }
                 isUserLoggedIn?.let {
                     val startDestination = if (it) Graph.BottomBar.route else Graph.Login.route
-                    AppContent(startDestination)
+                    AppContent(startDestination, { isUserLoggedIn = it })
```
Comment (bstolyarov) [inline app/src/main/kotlin/com/softteco/template/MainActivity.kt:52]: Why changing `isUserLoggedIn` via callback works better then 
`isUserLoggedIn = profileRepository.getUser() is Result.Success`?
It seems they should work similarly.

Comment (bstolyarov) [reply app/src/main/kotlin/com/softteco/template/MainActivity.kt:52]: It's a good catch! 
Could we add some SessionManager to handle if a user logged in? The SessionManager could be a singleton, injected to MainActivity and in places where we do login\logout. In MainActivity we will just collect a state field of SessionManager. 
So in this way, we will avoid adding the callback for handling whether the user logged in or logged out

**Review by bstolyarov — APPROVED** [review]

**Review by EvgeniyFilippov — APPROVED** [review]
